In [ ]:
import numpy as np

#Datatype and attributes

In [4]:
#numpys main datatype is ndarray

a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2=np.array([[1,2,3],[4,5,6]])
a2 # matrix->2darray

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,5,6],[4,5,6],[6,9.8,5]]])
a3# 3d array

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[3. , 5. , 6. ],
        [4. , 5. , 6. ],
        [6. , 9.8, 5. ]]])

In [10]:
a1.shape

(3,)

In [11]:
 a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [15]:
a1.ndim, a2.ndim, a3.ndim    # n-dimention

(1, 2, 3)

In [16]:
a1.dtype,a2.dtype,a3.dtype  # datatype in array

(dtype('int64'), dtype('int64'), dtype('float64'))

In [21]:
a1.size,a2.size,a3.size   #no of elem

(3, 6, 18)

In [22]:
type(a2),type(a3)

(numpy.ndarray, numpy.ndarray)

#create dataframe from numpy array

In [25]:
import pandas as pd

df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# 2  creating arrays

In [4]:
 import numpy as np
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [8]:
sample_array.dtype

dtype('int64')

In [10]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
ones.dtype

dtype('float64')

In [12]:
type(ones)

numpy.ndarray

In [6]:
import numpy as np
zeros=np.zeros((2,3))
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
zeros.dtype


dtype('float64')

In [9]:
type(zeros)

numpy.ndarray

In [11]:
range_array= np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [12]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[3, 0, 6, 7, 2],
       [0, 0, 7, 4, 3],
       [6, 3, 2, 9, 7]])

In [13]:
random_array.size

15

In [15]:
random_array.shape

(3, 5)

In [18]:
 random_array2=np.random.random((5,3))
random_array2

array([[0.91485341, 0.24724505, 0.99446695],
       [0.61698485, 0.52683438, 0.34180786],
       [0.70653382, 0.95947453, 0.8944302 ],
       [0.61798775, 0.10136948, 0.09114451],
       [0.79451908, 0.95984333, 0.59860668]])

In [20]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.5749521 , 0.90381662, 0.32208218],
       [0.87186748, 0.80321294, 0.13767457],
       [0.87517517, 0.57766068, 0.48967443],
       [0.06297639, 0.32422298, 0.63139979],
       [0.60174972, 0.7497704 , 0.11836545]])

In [ ]:
#psudo random numbers
np.random.seed()